server:
  port: 8675

spring:
  data:
    mongodb:
     host: mongodb

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5